import type { Config } from "tailwindcss";
import plugin from "tailwindcss/plugin";

const config: Config = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        container: {
            screens: {
                xsm: "475px",
                sm: "600px",
                md: "728px",
                lg: "984px",
                xl: "1240px",
            },
        },
        screens: {
            xsm: "475px",
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
        },
        extend: {
            textShadow: {
                sm: "0 1px 2px var(--tw-shadow-color)",
                DEFAULT: "0 2px 4px var(--tw-shadow-color)",
                lg: "0 8px 16px var(--tw-shadow-color)",
            },
            backgroundImage: {
                "home-hero": "url('/images/home/hero.webp')",
                "home-hero-mobile": "url('/images/home/hero-mobile.webp')",
                "home-hero-tablet": "url('/images/home/hero-tablet.webp')",
                "services-wood": "url('/images/services/wood-hover.webp')",
                "services-cnc": "url('/images/services/cnc-hover.webp')",
                "services-design": "url('/images/services/design-hover.webp')",
            },
            height: {
                header: "100px",
            },
            fontFamily: {
                sans: ["Inter", "system-ui"],
                serif: ["Raleway", "system-ui"],
            },
            screens: {
                xs: "480px",
                ss: "620px",
                sm: "768px",
                md: "1060px",
                lg: "1200px",
                xl: "1700px",
            },
            colors: {
                sfdPrimary0: "#C18434",
                sfdPrimary1: "#B88A4E",
                sfdPrimary2: "#CEAF86",
                sfdPrimary3: "#D5B895",
                sfdPrimary4: "#EADECC",
                sfdPrimary5: "#FBF9F7",

                sfdSecondary0: "#384346",
                sfdSecondary1: "#687877",
                sfdSecondary2: "#7C8B8B",
                sfdSecondary3: "#BABABA",
                sfdSecondary4: "#D8D8D8",
                sfdSecondary5: "#F5F5F5",

                sfdGray0: "#1A1A1A",
                sfdGray1: "#272727",
                sfdGray2: "#343434",
                sfdGray3: "#BABABA",
                sfdGray4: "#D8D8D8",
                sfdGray5: "#F5F5F5",
            },
        },
    },

    plugins: [
        plugin(function ({ matchUtilities, theme }) {
            matchUtilities(
                {
                    "text-shadow": (value) => ({
                        textShadow: value,
                    }),
                },
                { values: theme("textShadow") }
            );
        }),
    ],
    safelist: [
        "auto-cols-auto",
        "auto-cols-min",
        "auto-cols-max",
        "auto-cols-fr",
        "auto-rows-auto",
        "auto-rows-min",
        "auto-rows-max",
        "auto-rows-fr",
        "grid-flow-row",
        "grid-flow-col",
        "grid-flow-row-dense",
        "grid-flow-col-dense",
        "grid-flow-dense",
        "grid-rows-1",
        "grid-cols-3",
        "font-extrabold",
        "leading-none",
        "tracking-tight",
        "fixed",
        "mx-auto",
        "container",
        "w-full",
        "h-full",
        "w-screen",
        "h-screen",
        "flex",
        "flex-col",
        "flex-row",
        "flex-1",
        "flex-auto",
        "flex-initial",
        "flex-none",
        "inline-flex",
        "flex-grow-1",
        "flex-grow-0",
        "flex-shrink-1",
        "flex-shrink-0",
        "flex-wrap",
        "flex-nowrap",
        "justify-normal",
        "justify-start",
        "justify-end",
        "justify-center",
        "justify-between",
        "justify-around",
        "justify-evenly",
        "justify-stretch",
        "justify-items-start",
        "justify-items-end",
        "justify-items-center",
        "justify-items-stretch",
        "justify-self-auto",
        "justify-self-start",
        "justify-self-end",
        "justify-self-center",
        "justify-self-stretch",
        "content-normal",
        "content-center",
        "content-start",
        "content-end",
        "content-between",
        "content-around",
        "content-evenly",
        "content-baseline",
        "content-stretch",
        "items-start",
        "items-end",
        "items-center",
        "items-baseline",
        "items-stretch",
        "self-auto",
        "self-start",
        "self-auto",
        "self-end",
        "self-center",
        "self-stretch",
        "self-baseline",
    ],
};
export default config;
